### ISSUE TITLE
Network perimeter policy affects services using Execution Roles (Lambda, Codebuild, etc)

### ISSUE THREAD

**Issue by lorengordon** [aws-samples/data-perimeter-policy-examples#3]
Hello,
I was testing the [network perimeter policy](https://github.com/aws-samples/data-perimeter-policy-examples/blob/main/service_control_policies/network_perimeter_policy.json) as an SCP, and noticed that it seemed to prevent services with execution roles from using their credentials. Lambda, for example. I was expecting this condition to allow the execution role, but it seems not? Is there a simple condition key that would work and match any service? I'd rather not have to exempt execution roles using PrincipalArn or PrincipalTag...

```
                "Bool": {
                    "aws:ViaAWSService": "false"
                },
```

**Comment by liwadman** [comment]
Hello,

At this point in time there is no global condition key that identifies when a role was assumed by an AWS resource for it's execution role.

To do this today, you can use service specific condition keys where they exist, or use PrincipalTag/PrincipalARN for exceptions.

An example of a service specific condition key you could use is lambda:SourceFunctionArn . This is present in the authorization context when a role was assumed for a lambda function.

So if you had a policy with a condition like:

`                "Null": {
                    "lambda:SourceFunctionArn": "false"
                }
   `
The policy statement it belongs to would only apply to roles assumed for a lambda function, because that condition key is not null. You can of course also use StringEquals/Like, or ArnEquals/Like if you want to go more granular. Roles delivered to ec2 instances via IMDS have [ec2:SourceInstanceArn](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/iam-policy-structure.html#amazon-ec2-keys). Others exist for other AWS services that can be use, however it's important to note the service-specific condition key must be one that is present in the service role, and not just a condition key that is supported when calling that service.

We're looking to make this better and easier over time.

Hope this helps!

**Comment by lorengordon** [comment]
Thanks! How does that evaluate if using multiple condition keys with the Null operator? Would that work? I always get confused by how these evaluate. E.g.

```
                "Null": {
                    "lambda:SourceFunctionArn": "false",
                    "ec2:SourceInstanceArn": "false"
                },
```

**Comment by lorengordon** [comment]
Hmm, actually, it didn't work to add `"Null": { "lambda:SourceFunctionArn": "false" }` as part of the network perimeter SCP. The lambda was still unable to execute. Most annoyingly, the failure isn't logged to CloudTrail, so it's extra hard to see what is happening.

**Comment by liwadman** [comment]
Would you be able to share your SCP ( feel free to redact account identifiers such as role names, resource names, or account IDs).

I wrote a blog recently that uses an example Null with source instance ARN to craft an SCP that can only apply to ec2 instances, it might help as well:

https://aws.amazon.com/blogs/security/how-to-use-policies-to-restrict-where-ec2-instance-credentials-can-be-used-from/

**Comment by lorengordon** [comment]
```
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Effect": "Deny",
            "NotAction": [
                "es:ESHttp*",
                "dax:PutItem",
                "dax:Query",
                "dax:Scan",
                "dax:GetItem",
                "dax:DeleteItem",
                "dax:UpdateItem",
                "dax:BatchGetItem",
                "dax:BatchWriteItem",
                "dax:ConditionCheckItem"
              ],
              "Condition": {
                "Bool": {
                    "aws:ViaAWSService": "false"
                },
                "NotIpAddressIfExists": {
                    "aws:SourceIp": [
                        "<nat>"
                    ],
                    "aws:VpcSourceIp": [
                        "<vpc-cidrs>"
                    ]
                },
                "StringNotLikeIfExists": {
                    "lambda:SourceFunctionArn": "*"
                },
                "ArnNotLikeIfExists": {
                    "aws:PrincipalArn": [
                        "arn:*:iam::*:role/aws:ec2-infrastructure"
                    ]
                }
            },
            "Resource": "*",
            "Sid": "DenyUntrustedEnvironments"
        }
    ]
}
```

**Comment by lorengordon** [comment]
If I adjust the condition to use `StringNotLikeIfExists`, it seems to work...

```
        "StringNotLikeIfExists": {
          "lambda:SourceFunctionArn": "*"
        },
```

**Comment by liwadman** [comment]
That govcloud information is good to know - I've only tested my examples on the commercial (aws) partition, and don't have easy access to a govcloud account at the moment.

To confirm, that means The lambda function code can all other AWS services when you change to StringNotLikeIfExists?

**Comment by lorengordon** [comment]
It appears I was mistaken. StringNotLikeIfExists doesn't work either. With that condition, the lambda was failing to even get invoked, so the function metrics weren't even reporting the error, and I mistook the absence of errors for success. 😭

**Comment by liwadman** [comment]
ack, and that makes more sense. Because it's with "...ifExists", it means that any role that didn't have that condition would also pass (be denied).

If the lambda function is not being exempt with the null condition, to me it would indicate that condition key was not launched in govcloud. It's more-recent key from 2022, and govcloud typically does follow commercial in launches - however I cannot confirm this is the case here yet. But I also didn't see any explicit statement for govcloud in docs.

I do know the EC2 condition key did launch with GovCloud support however.

**Comment by lorengordon** [comment]
I have certainly found that condition keys I want to use may not be available in GovCloud, and similarly I also have not found any documentation on what condition keys are or are not available in GovCloud.

**Comment by liwadman** [comment]
I will try to follow up with the lambda team and report back.

**Comment by lorengordon** [comment]
@liwadman I can try, just to validate.

However, I am worried about impacting much more than just lambda. I was only using lambda as an example. We are still using the old "Compliant Framework" and its "Account Vending Machine" (now archived, in favor of the newer Landing Zone Accelerator). We have no way to test the vending machine without just creating a new account, and we have very little visibility into exactly what the vending machine does or how it does it. With the SCP blocking things at a level where CloudTrail doesn't even pick up the access denied logs, I am super hesitant to actually implement this SCP.

**Comment by lorengordon** [comment]
Ok, using the [same policy provided above](https://github.com/aws-samples/data-perimeter-policy-examples/issues/3#issuecomment-1498244146), I flipped the `Null` condition on `lambda:SourceFunctionArn` from `false` to `true`:

```
                "Null": {
                    "lambda:SourceFunctionArn": "true"
                },
```

Unfortunately, that still failed in a way where the lambda was no longer even being invoked. No invocation errors were being recorded, and no CloudTrail messages were logged recording the attempts (silent failure).

**Comment by liwadman** [comment]
To me this indicates that there are other roles that are failing their tasks due to access denied- that policy example would exempt the operations done by lambda, and make the network perimeter policy apply to them.

I would like to say we hear you loud and clear on your earlier comment. We are working to make the SCP experience better. If you've got a support contract, I'd be happy to keep this discussion going with through your account team as well.

**Comment by lorengordon** [comment]
I'll forward this issue to our account team so they can reach out to you. Thanks for your assistance and guidance! I really appreciate your responsiveness.

Fwiw, I did test using the PrincipalTag approach, and that worked with the lambda execution role -- it was invoked and was able to handle the sqs message properly, interacting with other AWS services as well. But my concern still holds with everything the Compliant Framework is doing behind the scenes, and somehow figuring out which roles we need to tag.

**Comment by liwadman** [comment]
Also  commenting here for visibility, but I researched this a bit more. The lambda execution role makes some calls to AWS services without lambda:SourceFunctionArn set, which is likely why this was not working as it was expected. Because these two issues are working on essentialy the same problem, I'll keep this one closed and keep https://github.com/aws-samples/data-perimeter-policy-examples/issues/4 as the working thread.
