### ISSUE TITLE
Non-VPC-attached Lambda functions

### ISSUE THREAD

**Issue by olorin5** [aws-samples/data-perimeter-policy-examples#4]
How can the network perimeter SCP be configured to not block actions coming from non-VPC-attached Lambda functions?  The source IP of such functions appears to be a AWS internal IP range.  

Attempting to exclude Lambda source ARNs does not appear to have an effect as the source ARN appears to be the Lambda's execution role and not the Lambda function ARN:
"ArnNotLikeIfExists": {
    "aws:PrincipalArn": [
        "arn:aws:iam::*:role/aws:ec2-infrastructure"    
    ],
    "aws:SourceArn": [
        "arn:aws:lambda:*:*:function:*"    
    ]
}

**Comment by liwadman** [comment]
aws:SourceArn is a value that is only set when an AWS Service Principal interacts with a resource in your account. No IAM principal that would be subject to a service control policy should have any value populated for aws:SourceArn.

To exclude your lambda roles from your network perimeter, we recommend using a null operator on the lambda:SourceFunctionArn condition key like so:

`
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "EnforceNetworkPerimeterOnLambdaRoles",
            "Effect": "Deny",
            "NotAction": [
                "es:ES*",
                "dax:GetItem",
                "dax:BatchGetItem",
                "dax:Query",
                "dax:Scan",
                "dax:PutItem",
                "dax:UpdateItem",
                "dax:DeleteItem",
                "dax:BatchWriteItem",
                "dax:ConditionCheckItem",
                "logs:CreateLogGroup",
                "logs:CreateLogStream",
                "logs:PutLogEvents",
                "elasticfilesystem:ClientMount",
                "xray:PutTraceSegments"
            ],
            "Resource": "*",
            "Condition": {
                "BoolIfExists": {
                    "aws:ViaAWSService": "false"
                },
                "NotIpAddressIfExists": {
                    "aws:SourceIp": [
                        "<my-corporate-cidr>"
                    ]
                },
                "StringNotEqualsIfExists": {
                    "aws:PrincipalTag/network-perimeter-exception": "true",
                    "aws:SourceVpc": [
                        "<my-vpc>"
                    ]
                },
                "Null": {
                    "lambda:SourceFunctionArn": "true"
                }
            }
        }
    ]
}
`

There was an earlier issue about the same topic, but I believe there may be additional interactions in that customers environment that were being denied.

The above example when fitted to your environment should always not-deny any interaction from a lambda because it will have the 'lambda:SourceFunctionArn' populated.

Please test in a lower environment before applying to production, this example policy should help you out but should be considered an example only until it's gone through your testing.

**Comment by liwadman** [comment]
Heya, you may have seen that I just deleted my earlier response.

For allow listing Lambda outside of a VPC in a network perimeter, we recommend going with a ARN or Tag based approach to allow listing. The reason for this is that the lambda execution role itself is responsible for things like calls used to bootstrap the lambda environment, like decryption of KMS protected variables and calls to read the event source mapping as per [This document](https://docs.aws.amazon.com/lambda/latest/dg/lambda-intro-execution-role.html#permissions-executionrole-source-function-arn) .

**Comment by liwadman** [comment]
Closing because I believe it is solved, but feel free to re-open if there is anything else.
